var BareMetal = (typeof BareMetal !== 'undefined') ? BareMetal : {};
BareMetal.Media = (function(){
'use strict';
var g=typeof globalThis!=='undefined'?globalThis:(typeof window!=='undefined'?window:this);
function n(){return g.navigator||{}}function m(){return n().mediaDevices||{}}function d(){return g.document||null}function q(v){return Promise.resolve(v)}function a(v){return Array.prototype.slice.call(v||[])}function bytes(n){try{return new Uint8Array(n||0)}catch(_){return[]}}function err(name){return new Error(name+' is not supported')}function stopTracks(stream){a(stream&&stream.getTracks&&stream.getTracks()).forEach(function(t){try{t&&t.stop&&t.stop()}catch(_){}});return stream}function stopVideo(video){try{video&&video.pause&&video.pause()}catch(_){}try{if(video)video.srcObject=null}catch(_){}}function size(v,alt){return typeof v==='number'?v+(alt===false?'':'px'):(v||'')}function copy(o){var x={},k;for(k in o||{})x[k]=o[k];return x}function pick(o,keys){var x={},i,k;for(i=0;i<keys.length;i++){k=keys[i];if(o&&o[k]!==undefined)x[k]=o[k]}return x}function makeVideo(opts){var o=d(),v=o&&o.createElement?o.createElement('video'):null,p;if(!v)return q(null);v.autoplay=true;v.playsInline=true;v.muted=!opts||opts.muted!==false;v.srcObject=opts&&opts.stream||null;p=v.play&&v.play();return p&&p.then?p.then(function(){return v}).catch(function(){return v}):q(v)}function videoConstraints(opts){var v=pick(opts,['width','height','frameRate','facingMode']);if(opts&&opts.deviceId!==undefined)v.deviceId=typeof opts.deviceId==='string'?{exact:opts.deviceId}:opts.deviceId;return Object.keys(v).length?v:true}function audioConstraints(opts){var x=pick(opts,['deviceId','echoCancellation','noiseSuppression','autoGainControl','sampleRate','channelCount','latency']);if(x.deviceId&&typeof x.deviceId==='string')x.deviceId={exact:x.deviceId};return Object.keys(x).length?x:true}function first(stream,kind){var xs=kind==='audio'?a(stream&&stream.getAudioTracks&&stream.getAudioTracks()):a(stream&&stream.getVideoTracks&&stream.getVideoTracks());return xs[0]||null}function trackInfo(track){var out={kind:track&&track.kind||'',label:track&&track.label||'',constraints:{},settings:{},capabilities:{}};try{if(track&&track.getConstraints)out.constraints=track.getConstraints()||{}}catch(_){}try{if(track&&track.getSettings)out.settings=track.getSettings()||{}}catch(_){}try{if(track&&track.getCapabilities)out.capabilities=track.getCapabilities()||{}}catch(_){}return out}
function camera(opts){var api=m(),fn=api.getUserMedia;if(!fn)return Promise.reject(err('getUserMedia'));return fn.call(api,{video:videoConstraints(opts||{}),audio:false}).then(function(stream){return makeVideo({stream:stream,muted:true}).then(function(video){return{stream:stream,video:video,stop:function(){stopVideo(video);return stopTracks(stream)}}})})}
function audioContext(stream){var C=g.AudioContext||g.webkitAudioContext,ctx=null,source=null,analyser=null;if(C)try{ctx=new C();source=ctx.createMediaStreamSource?ctx.createMediaStreamSource(stream):null;analyser=ctx.createAnalyser?ctx.createAnalyser():null;if(source&&analyser&&source.connect)source.connect(analyser)}catch(_){ctx=null;source=null;analyser=null}return{ctx:ctx,source:source,analyser:analyser,getFrequency:function(){var out=bytes(analyser&&analyser.frequencyBinCount||0);try{analyser&&analyser.getByteFrequencyData&&analyser.getByteFrequencyData(out)}catch(_){}return out},getWaveform:function(){var out=bytes(analyser&&analyser.fftSize||2048);try{analyser&&analyser.getByteTimeDomainData&&analyser.getByteTimeDomainData(out)}catch(_){}return out}}}
function microphone(opts){var api=m(),fn=api.getUserMedia;if(!fn)return Promise.reject(err('getUserMedia'));return fn.call(api,{video:false,audio:audioConstraints(opts||{})}).then(function(stream){var ac=audioContext(stream);return{stream:stream,stop:function(){try{ac.ctx&&ac.ctx.close&&ac.ctx.close()}catch(_){}return stopTracks(stream)},getLevel:function(){var data=ac.getWaveform(),i,sum=0,v;for(i=0;i<data.length;i++){v=((data[i]||0)-128)/128;sum+=v*v}return data.length?Math.min(1,Math.sqrt(sum/data.length)):0}}})}
function screen(opts){var api=m(),fn=api.getDisplayMedia,o=opts||{};if(!fn)return Promise.reject(err('getDisplayMedia'));return fn.call(api,{video:videoConstraints(o),audio:o.audio===undefined?false:o.audio}).then(function(stream){return{stream:stream,stop:function(){return stopTracks(stream)}}})}
function snapshot(videoEl,opts){var o=opts||{},doc=d(),canvas=doc&&doc.createElement?doc.createElement('canvas'):null,ctx,w,h;if(!canvas||!videoEl)return o.as==='blob'||o.blob?q(null):(o.as==='dataURL'||o.dataURL?'':null);w=o.width||videoEl.videoWidth||videoEl.naturalWidth||videoEl.width||videoEl.clientWidth||0;h=o.height||videoEl.videoHeight||videoEl.naturalHeight||videoEl.height||videoEl.clientHeight||0;canvas.width=w;canvas.height=h;ctx=canvas.getContext&&canvas.getContext('2d');if(!ctx)return o.as==='blob'||o.blob?q(null):(o.as==='dataURL'||o.dataURL?'':canvas);try{ctx.drawImage(videoEl,0,0,w,h)}catch(_){}if(o.as==='blob'||o.blob)return new Promise(function(resolve){try{if(canvas.toBlob)return canvas.toBlob(function(b){resolve(b||null)},o.format||'image/png',o.quality);resolve(null)}catch(_){resolve(null)}});if(o.as==='dataURL'||o.dataURL)try{return canvas.toDataURL(o.format||'image/png',o.quality)}catch(_){return''}return canvas}
function record(stream,opts){var o=opts||{},R=g.MediaRecorder,rec,chunks=[],subs=[];if(!R)throw err('MediaRecorder');rec=new R(stream,pick(o,['mimeType','audioBitsPerSecond','videoBitsPerSecond','bitsPerSecond']));rec.ondataavailable=function(ev){var b=ev&&ev.data;if(b&&(b.size===undefined||b.size>0))chunks.push(b);subs.slice().forEach(function(fn){try{fn(b,ev)}catch(_){} })};function blob(){return new Blob(chunks,{type:rec.mimeType||o.mimeType||'video/webm'})}var api={recorder:rec,start:function(){if(rec.state==='inactive'&&rec.start)rec.start(o.timeslice);return api},stop:function(){if(rec.state==='inactive')return q(blob());return new Promise(function(resolve,reject){var prevStop=rec.onstop,prevErr=rec.onerror,done=false;rec.onstop=function(ev){rec.onstop=prevStop;rec.onerror=prevErr;try{prevStop&&prevStop(ev)}catch(_){}if(done)return;done=true;resolve(blob())};rec.onerror=function(ev){rec.onstop=prevStop;rec.onerror=prevErr;try{prevErr&&prevErr(ev)}catch(_){}if(done)return;done=true;reject(ev&&ev.error||ev||new Error('Recording error'))};try{rec.stop&&rec.stop()}catch(e){rec.onstop=prevStop;rec.onerror=prevErr;reject(e)}})},pause:function(){if(rec.state==='recording'&&rec.pause)rec.pause();return api},resume:function(){if(rec.state==='paused'&&rec.resume)rec.resume();return api},onData:function(fn){if(typeof fn==='function')subs.push(fn);return function(){var i=subs.indexOf(fn);if(i>=0)subs.splice(i,1)}},getBlob:blob};return api}
function devices(){var api=m(),fn=api.enumerateDevices;if(!fn)return q({cameras:[],microphones:[],speakers:[]});return fn.call(api).then(function(list){var out={cameras:[],microphones:[],speakers:[]};a(list).forEach(function(it){if(!it)return;if(it.kind==='videoinput')out.cameras.push(it);else if(it.kind==='audioinput')out.microphones.push(it);else if(it.kind==='audiooutput')out.speakers.push(it)});return out}).catch(function(){return{cameras:[],microphones:[],speakers:[]}})}
function switchCamera(stream,deviceId){var oldTrack=first(stream,'video'),api=m(),fn=api.getUserMedia,cons,temp,newTrack,audio;if(!fn)return Promise.reject(err('getUserMedia'));cons=oldTrack&&oldTrack.getConstraints?copy(oldTrack.getConstraints()||{}):{};if(deviceId!==undefined)cons.deviceId=typeof deviceId==='string'?{exact:deviceId}:deviceId;return fn.call(api,{video:Object.keys(cons).length?cons:true,audio:false}).then(function(next){temp=next;newTrack=first(temp,'video');audio=a(stream&&stream.getAudioTracks&&stream.getAudioTracks());if(stream&&stream.removeTrack&&oldTrack)try{stream.removeTrack(oldTrack)}catch(_){}if(stream&&stream.addTrack&&newTrack)try{stream.addTrack(newTrack)}catch(_){return temp}if(oldTrack&&oldTrack.stop)try{oldTrack.stop()}catch(_){}a(temp&&temp.getTracks&&temp.getTracks()).forEach(function(t){if(t!==newTrack)try{t.stop&&t.stop()}catch(_){}});if(stream&&stream.getTracks)return stream;if(typeof g.MediaStream!=='undefined')return new g.MediaStream(audio.concat(newTrack?[newTrack]:[]));return temp})}
function pip(videoEl){if(!videoEl||!videoEl.requestPictureInPicture)return Promise.reject(err('Picture-in-Picture'));return Promise.resolve(videoEl.requestPictureInPicture())}
function torch(stream,on){var track=first(stream,'video'),C=g.ImageCapture,caps;if(!track||!track.applyConstraints||!C)return q(false);try{caps=new C(track)}catch(_){caps=null}return Promise.resolve(caps&&caps.getPhotoCapabilities?caps.getPhotoCapabilities():null).catch(function(){return null}).then(function(info){var tcap={};try{if(track.getCapabilities)tcap=track.getCapabilities()||{}}catch(_){}if(!(info&&info.torch)&&!tcap.torch)return false;return track.applyConstraints({advanced:[{torch:!!on}]}).then(function(){return true}).catch(function(){return false})})}
function preview(stream,container,opts){var o=opts||{},doc=d(),root=typeof container==='string'&&doc&&doc.querySelector?doc.querySelector(container):container,el=doc&&doc.createElement?doc.createElement('video'):null,p;if(!el)return{el:null,destroy:function(){}};el.autoplay=true;el.playsInline=true;el.muted=o.muted!==false;el.controls=!!o.controls;if(o.className)el.className=o.className;el.style.objectFit=o.fit||'cover';if(o.mirror)el.style.transform='scaleX(-1)';if(o.width)el.style.width=size(o.width);else if(root)el.style.width='100%';if(o.height)el.style.height=size(o.height);el.srcObject=stream;if(root&&root.appendChild)root.appendChild(el);p=el.play&&el.play();if(p&&p.catch)p.catch(function(){});return{el:el,destroy:function(){stopVideo(el);if(el.parentNode)el.parentNode.removeChild(el)}}}
function constraints(stream){return{video:a(stream&&stream.getVideoTracks&&stream.getVideoTracks()).map(trackInfo),audio:a(stream&&stream.getAudioTracks&&stream.getAudioTracks()).map(trackInfo)}}
return{camera:camera,microphone:microphone,screen:screen,snapshot:snapshot,record:record,devices:devices,switchCamera:switchCamera,pip:pip,torch:torch,preview:preview,constraints:constraints,audioContext:audioContext};
})();
if(typeof module!=='undefined') module.exports = BareMetal.Media;
