var BareMetal = (typeof BareMetal !== 'undefined') ? BareMetal : {};
BareMetal.Speech = (function(){
  'use strict';
var g=typeof globalThis!=='undefined'?globalThis:(typeof window!=='undefined'?window:this);
function y(v){return v==null?'':String(v)}function a(v){return Array.isArray(v)?v:(v==null?[]:[v])}function k(){return g.speechSynthesis||null}function u(){return g.SpeechSynthesisUtterance||null}function r(){return g.SpeechRecognition||g.webkitSpeechRecognition||null}function h(){return g.SpeechGrammarList||g.webkitSpeechGrammarList||null}
function x(list){var args=Array.prototype.slice.call(arguments,1),i=0;for(;i<(list||[]).length;i++)try{list[i].apply(null,args)}catch(_){}}
function m(v){return y(v).toLowerCase().replace(/[_-]/g,' ').replace(/[^\w\s]+/g,' ').replace(/\s+/g,' ').trim()}
function q(lang){var s=k(),list=s&&s.getVoices?s.getVoices()||[]:[],i;lang=lang==null?'':y(lang).toLowerCase();if(!lang)return list.slice();return list.filter(function(v){i=y(v&&v.lang).toLowerCase();return i===lang||i.indexOf(lang+'-')===0||i.indexOf(lang)===0})}
function j(voice){var list=q(),i=0,it,key;if(!voice)return null;if(typeof voice==='object')return voice;key=y(voice).toLowerCase();for(;i<list.length;i++){it=list[i];if(y(it&&it.name).toLowerCase()===key||y(it&&it.voiceURI).toLowerCase()===key)return it}return null}
function p(result){var i=0,out=[];for(;result&&i<result.length;i++)out.push({transcript:y(result[i]&&result[i].transcript).trim(),confidence:result[i]&&result[i].confidence!=null?+result[i].confidence:0});return out}
function f(ev,i){var item=ev&&ev.results&&ev.results[i],alts=p(item),first=alts[0]||{transcript:'',confidence:0};return{transcript:first.transcript,text:first.transcript,confidence:first.confidence,isFinal:!!(item&&item.isFinal),alternatives:alts,result:item,event:ev}}
function w(rec,grammars){var C=h(),list=null,arr=a(grammars),i=0,it,weight;if(!grammars||rec==null||(!('grammars'in rec)&&rec.grammars==null))return;if(typeof grammars.addFromString==='function'||typeof grammars.addFromURI==='function'){rec.grammars=grammars;return}if(C)try{list=new C();}catch(_){list=null}if(list){for(;i<arr.length;i++){it=arr[i];weight=it&&it.weight!=null?it.weight:1;if(typeof it==='string'){if(list.addFromString)list.addFromString(it,weight)}else if(it&&it.src&&list.addFromString)list.addFromString(it.src,weight);else if(it&&it.uri&&list.addFromURI)list.addFromURI(it.uri,weight)}rec.grammars=list;return}rec.grammars=grammars}
function canSpeak(){return!!(k()&&u())}function canRecognize(){return!!r()}
function speak(text,opts){opts=opts||{};return new Promise(function(resolve,reject){var s=k(),U=u(),utter,voice;if(!s||!U)return reject(new Error('Speech synthesis not supported'));try{utter=new U(y(text));voice=j(opts.voice);if(voice)utter.voice=voice;if(opts.lang!=null)utter.lang=y(opts.lang);else if(voice&&voice.lang)utter.lang=voice.lang;if(opts.rate!=null)utter.rate=+opts.rate;if(opts.pitch!=null)utter.pitch=+opts.pitch;if(opts.volume!=null)utter.volume=+opts.volume;if(typeof opts.onBoundary==='function')utter.onboundary=function(ev){opts.onBoundary(ev,utter)};if(typeof opts.onMark==='function')utter.onmark=function(ev){opts.onMark(ev,utter)};utter.onend=function(){resolve()};utter.onerror=function(ev){reject(ev&&ev.error?ev.error:ev||new Error('Speech synthesis error'))};s.speak(utter)}catch(err){reject(err)}})}
function pause(){var s=k();if(s&&s.pause)s.pause()}function resume(){var s=k();if(s&&s.resume)s.resume()}function cancel(){var s=k();if(s&&s.cancel)s.cancel()}function isSpeaking(){var s=k();return!!(s&&(s.speaking||s.pending))}
function listen(opts){opts=opts||{};var C=r(),rec,res=[],end=[],err=[],inter=[],api;if(!C)throw new Error('Speech recognition not supported');rec=new C();if(opts.lang!=null)rec.lang=y(opts.lang);if(opts.continuous!=null)rec.continuous=!!opts.continuous;if(opts.interimResults!=null)rec.interimResults=!!opts.interimResults;if(opts.maxAlternatives!=null)rec.maxAlternatives=+opts.maxAlternatives;w(rec,opts.grammars);rec.onresult=function(ev){var i=(ev&&ev.resultIndex)||0,item;for(;ev&&ev.results&&i<ev.results.length;i++){item=f(ev,i);x(item.isFinal?res:inter,item,ev,rec)}};rec.onend=function(ev){x(end,ev,rec)};rec.onerror=function(ev){x(err,ev,rec)};api={stop:function(){try{if(rec.stop)rec.stop()}catch(_){}return api;},abort:function(){try{if(rec.abort)rec.abort()}catch(_){}return api;},onResult:function(cb){if(typeof cb==='function')res.push(cb);return api;},onEnd:function(cb){if(typeof cb==='function')end.push(cb);return api;},onError:function(cb){if(typeof cb==='function')err.push(cb);return api;},onInterim:function(cb){if(typeof cb==='function')inter.push(cb);return api;}};try{rec.start()}catch(e){setTimeout(function(){x(err,e,rec)},0)}return api}
function b(text,phrases){var v=m(text),i=0,it,phrase,norm,best=null;for(;i<(phrases||[]).length;i++){it=phrases[i];phrase=typeof it==='string'?it:y(it&&(it.phrase||it.text));norm=m(phrase);if(norm&&(v===norm||v.indexOf(norm)>=0||norm.indexOf(v)>=0)&&(!best||norm.length>best.norm.length))best={phrase:phrase,norm:norm}}return best?best.phrase:null}
function command(phrases,callback,opts){var o=opts||{},list=a(phrases),session;o.continuous=o.continuous!==false;if(o.interimResults==null)o.interimResults=false;session=listen(o);session.onResult(function(result){var hit=b(result.transcript,list);if(hit&&callback)callback(hit,result.confidence,result.transcript,result)});return{stop:function(){session.stop()}}}
function dictate(opts){var o=opts||{},parts=[],text='',cbs=[],session,api;o.continuous=o.continuous!==false;if(o.interimResults==null)o.interimResults=true;function join(extra){return parts.concat(extra?[extra]:[]).join(' ').replace(/\s+/g,' ').trim()}session=listen(o);session.onResult(function(result){if(!result.transcript)return;parts.push(result.transcript);text=join();x(cbs,{text:text,transcript:result.transcript,final:true,confidence:result.confidence},text,result.transcript)});session.onInterim(function(result){var next;if(!result.transcript)return;next=join(result.transcript);x(cbs,{text:next,transcript:result.transcript,final:false,confidence:result.confidence},next,result.transcript)});api={stop:function(){session.stop();return api;},onText:function(cb){if(typeof cb==='function')cbs.push(cb);return api;},getText:function(){return text;},clear:function(){parts=[];text='';return api;}};return api}
function queue(items){var list=a(items).map(function(it){return typeof it==='string'?{text:it,opts:{}}:{text:y(it&&it.text),opts:it&&it.opts||{}}}),cbs=[],stopped=false,run=null,api;function emit(v){x(cbs,v)}function step(i){if(stopped||i>=list.length){emit({index:i,total:list.length,done:true,stopped:stopped});return Promise.resolve()}emit({index:i,total:list.length,item:list[i],status:'start'});return speak(list[i].text,list[i].opts).then(function(){emit({index:i,total:list.length,item:list[i],status:'spoken'});return step(i+1)})}api={start:function(){if(run)return run;stopped=false;run=step(0).finally(function(){run=null});return run;},stop:function(){stopped=true;cancel();return api;},onProgress:function(cb){if(typeof cb==='function')cbs.push(cb);return api;}};return api}
return{speak:speak,pause:pause,resume:resume,cancel:cancel,voices:q,isSpeaking:isSpeaking,listen:listen,command:command,dictate:dictate,canRecognize:canRecognize,canSpeak:canSpeak,queue:queue};
})();
if(typeof module!=='undefined') module.exports = BareMetal.Speech;
