var BareMetal = (typeof BareMetal !== 'undefined') ? BareMetal : {};
BareMetal.Gamepad = (function(){
  'use strict';
var g=typeof globalThis!=='undefined'?globalThis:(typeof window!=='undefined'?window:this);
var listeners={connect:[],disconnect:[],buttondown:[],buttonup:[],axismove:[]},states={},combos=[],rafId=0,timerId=0,running=false,lastTick=0,cfg={pollRate:16,deadzone:0.1};
var profiles={
  xbox:{buttons:{0:'A',1:'B',2:'X',3:'Y',4:'LB',5:'RB',6:'LT',7:'RT',8:'Back',9:'Start',10:'L3',11:'R3',12:'Up',13:'Down',14:'Left',15:'Right',16:'Guide'},axes:{0:'leftX',1:'leftY',2:'rightX',3:'rightY'}},
  ps:{buttons:{0:'Cross',1:'Circle',2:'Square',3:'Triangle',4:'L1',5:'R1',6:'L2',7:'R2',8:'Share',9:'Options',10:'L3',11:'R3',12:'Up',13:'Down',14:'Left',15:'Right',16:'PS'},axes:{0:'leftX',1:'leftY',2:'rightX',3:'rightY'}},
  generic:{buttons:{0:'Button0',1:'Button1',2:'Button2',3:'Button3',4:'Button4',5:'Button5',6:'Button6',7:'Button7',8:'Button8',9:'Button9',10:'Button10',11:'Button11',12:'Button12',13:'Button13',14:'Button14',15:'Button15',16:'Button16'},axes:{0:'leftX',1:'leftY',2:'rightX',3:'rightY'}}
};
var buttonAliases={a:0,cross:0,b:1,circle:1,x:2,square:2,y:3,triangle:3,lb:4,l1:4,rb:5,r1:5,lt:6,l2:6,rt:7,r2:7,back:8,select:8,share:8,start:9,options:9,menu:9,ls:10,l3:10,rs:11,r3:11,up:12,dpadup:12,down:13,dpaddown:13,left:14,dpadleft:14,right:15,dpadright:15,guide:16,home:16,ps:16};
var axisAliases={leftx:0,lx:0,movex:0,lefty:1,ly:1,movey:1,rightx:2,rx:2,lookx:2,righty:3,ry:3,looky:3};
function n(){return g.navigator||{}}function num(v,d){v=Number(v);return isFinite(v)?v:(d||0)}function clamp(v,min,max){v=num(v,0);return v<min?min:v>max?max:v}function now(){return Date.now?Date.now():(new Date()).getTime()}function arr(v){return Array.prototype.slice.call(v||[])}function keys(o){return Object.keys(o||{})}
function getGamepads(){try{return n().getGamepads?n().getGamepads()||[]:[]}catch(_){return[]}}
function profileName(gamepad){var id=String(gamepad&&gamepad.id||'').toLowerCase();return /xbox|xinput|x-input|360/.test(id)?'xbox':/playstation|dualshock|dualsense|wireless controller|sony|ps[345]/.test(id)?'ps':'generic'}
function buttonName(profile,i){var p=profiles[profile]||profiles.generic;return p.buttons[i]||('Button'+i)}function axisName(profile,i){var p=profiles[profile]||profiles.generic;return p.axes[i]||('axis'+i)}
function cloneButton(b){return{index:num(b&&b.index,0),name:String(b&&b.name||''),pressed:!!(b&&b.pressed),touched:!!(b&&b.touched),value:num(b&&b.value,0)}}
function cloneState(state){return state?{id:String(state.id||''),index:num(state.index,0),buttons:(state.buttons||[]).map(cloneButton),axes:arr(state.axes).map(function(v){return num(v,0)}),connected:!!state.connected,timestamp:num(state.timestamp,0),mapping:String(state.mapping||''),profile:String(state.profile||'generic')}:null}
function emit(event,data){var list=listeners[event]||[],i=0,payload=data||{};payload.type=event;for(;i<list.length;i++)try{list[i](payload)}catch(_){}}
function on(event,callback){if(typeof callback!=='function')return function(){};(listeners[event]=listeners[event]||[]).push(callback);return function(){off(event,callback)}}
function off(event,callback){var list=listeners[event],i;if(!list||!list.length)return;for(i=list.length-1;i>=0;i--)if(list[i]===callback)list.splice(i,1)}
function deadzone(value,threshold){var v=clamp(value,-1,1),t=clamp(threshold==null?cfg.deadzone:threshold,0,1),a=Math.abs(v);if(!t)return v;if(a<=t)return 0;return(v<0?-1:1)*((a-t)/(1-t||1))}
function normalize(gamepad){var gp=gamepad||{},profile=profileName(gp),p=profiles[profile]||profiles.generic,bs=arr(gp.buttons),as=arr(gp.axes),i,maxB=Math.max(bs.length,keys(p.buttons).length),maxA=Math.max(as.length,keys(p.axes).length),buttons=[],axes=[],b,v,pressed,touched;for(i=0;i<maxB;i++){b=bs[i];v=typeof b==='number'?b:num(b&&('value'in b?b.value:(b&&b.pressed?1:0)),0);v=clamp(v,0,1);pressed=!!((b&&b.pressed)||v>=0.5);touched=!!(b&&('touched'in b?b.touched:pressed));buttons.push({index:i,name:buttonName(profile,i),pressed:pressed,touched:touched,value:v})}for(i=0;i<maxA;i++)axes.push(clamp(as[i],-1,1));return{id:String(gp.id||''),index:num(gp.index,0),buttons:buttons,axes:axes,connected:gp.connected!==false,timestamp:num(gp.timestamp,0),mapping:String(gp.mapping||''),profile:profile}}
function resolveButton(button){var k=String(button==null?'':button).toLowerCase().replace(/[\s_-]+/g,'');return typeof button==='number'?button:(buttonAliases.hasOwnProperty(k)?buttonAliases[k]:(/^button\d+$/.test(k)?num(k.slice(6),-1):(/^\d+$/.test(k)?num(k,-1):-1)))}
function resolveAxis(axis){var k=String(axis==null?'':axis).toLowerCase().replace(/[\s_-]+/g,'');return typeof axis==='number'?axis:(axisAliases.hasOwnProperty(k)?axisAliases[k]:(/^axis\d+$/.test(k)?num(k.slice(4),-1):(/^\d+$/.test(k)?num(k,-1):-1)))}
function snapshot(index){var state=states[index],pad;if(state)return state;pad=getGamepads()[index];if(!pad||pad.connected===false)return null;state=normalize(pad);state.axes=state.axes.map(function(v){return deadzone(v,cfg.deadzone)});state.raw=pad;return state}
function fireButton(event,state,i,value,prev){var detail={index:state.index,button:i,name:buttonName(state.profile,i),value:num(value,0),previous:num(prev,0),gamepad:cloneState(state),timestamp:state.timestamp||now()};emit(event,detail);if(event==='buttondown')feedCombos(detail)}
function fireAxis(state,i,value,prev){emit('axismove',{index:state.index,axis:i,name:axisName(state.profile,i),value:num(value,0),previous:num(prev,0),gamepad:cloneState(state),timestamp:state.timestamp||now()})}
function compare(next){var seen={},idx,cur,prev,i,max,b1,b2,a1,a2,gone;for(idx in next){if(!Object.prototype.hasOwnProperty.call(next,idx))continue;seen[idx]=1;cur=next[idx];prev=states[idx];if(!prev)emit('connect',{index:cur.index,gamepad:cloneState(cur),timestamp:cur.timestamp||now()});max=Math.max(cur.buttons.length,prev?prev.buttons.length:0);for(i=0;i<max;i++){b1=prev&&prev.buttons[i]?prev.buttons[i]:null;b2=cur.buttons[i]||null;if((!b1||!b1.pressed)&&b2&&b2.pressed)fireButton('buttondown',cur,i,b2.value,b1&&b1.value);else if(b1&&b1.pressed&&(!b2||!b2.pressed))fireButton('buttonup',cur,i,b2&&b2.value,b1.value)}max=Math.max(cur.axes.length,prev?prev.axes.length:0);for(i=0;i<max;i++){a1=prev?num(prev.axes[i],0):0;a2=num(cur.axes[i],0);if(Math.abs(a2-a1)>0.0001)fireAxis(cur,i,a2,a1)}}for(idx in states){if(!Object.prototype.hasOwnProperty.call(states,idx)||seen[idx])continue;gone=cloneState(states[idx]);if(gone){gone.connected=false;emit('disconnect',{index:gone.index,gamepad:gone,timestamp:now()})}}}
function poll(){var pads=getGamepads(),next={},i,gp,state,out=[];for(i=0;i<pads.length;i++){gp=pads[i];if(!gp||gp.connected===false)continue;state=normalize(gp);state.axes=state.axes.map(function(v){return deadzone(v,cfg.deadzone)});state.raw=gp;next[state.index]=state}compare(next);states=next;keys(next).sort(function(a,b){return Number(a)-Number(b)}).forEach(function(k){out.push(cloneState(next[k]))});return out}
function getState(index){return cloneState(snapshot(index))}
function isPressed(index,button){var state=snapshot(index),i=resolveButton(button);return !!(state&&i>=0&&state.buttons[i]&&state.buttons[i].pressed)}
function getAxis(index,axisIndex){var state=snapshot(index),i=resolveAxis(axisIndex);return state&&i>=0?num(state.axes[i],0):0}
function isAxisKey(key,value){var k=String(key||'').toLowerCase(),v=String(value==null?'':value).toLowerCase();return /^axis:/i.test(v)||axisAliases.hasOwnProperty(v.replace(/[\s_-]+/g,''))||/(axis|move|look|stick|thumb|tilt|leftx|lefty|rightx|righty|lx|ly|rx|ry|horizontal|vertical)/.test(k)}
function vibrate(index,opts){var gp=(states[index]&&states[index].raw)||getGamepads()[index],o=opts||{},duration=Math.max(0,num(o.duration,100)),weak=clamp(o.weakMagnitude==null?0.5:o.weakMagnitude,0,1),strong=clamp(o.strongMagnitude==null?0.5:o.strongMagnitude,0,1),act=gp&&(gp.vibrationActuator||((gp.hapticActuators&&gp.hapticActuators[0])||null));if(!act)return Promise.resolve(false);if(act.playEffect)return Promise.resolve(act.playEffect('dual-rumble',{duration:duration,startDelay:0,weakMagnitude:weak,strongMagnitude:strong})).catch(function(){return false});if(act.pulse)return Promise.resolve(act.pulse(Math.max(weak,strong),duration)).catch(function(){return false});return Promise.resolve(false)}
function map(index,mapping){var out={},k,v;if(!mapping)return out;for(k in mapping){if(!Object.prototype.hasOwnProperty.call(mapping,k))continue;v=mapping[k];if(v&&typeof v==='object'){if(v.axis!=null)out[k]=getAxis(index,v.axis);else if(v.button!=null)out[k]=isPressed(index,v.button);else if(v.type==='axis'&&v.index!=null)out[k]=getAxis(index,v.index);else if(v.index!=null)out[k]=isPressed(index,v.index);else out[k]=undefined;continue}if(typeof v==='string'&&/^axis:/i.test(v)){out[k]=getAxis(index,v.split(':')[1]);continue}out[k]=isAxisKey(k,v)?getAxis(index,v):isPressed(index,v)}return out}
function sameCombo(detail,token){return detail.button===resolveButton(token)}
function feedCombos(detail){var t=detail.timestamp||now(),i,item;for(i=combos.length-1;i>=0;i--){item=combos[i];if(!item||item.index!==detail.index)continue;if(item.last&&t-item.last>item.timeout)item.step=0;if(sameCombo(detail,item.sequence[item.step])){item.step++;item.last=t;if(item.step>=item.sequence.length){try{item.callback({index:item.index,sequence:item.sequence.slice(),gamepad:detail.gamepad,button:detail.button,name:detail.name,timestamp:t})}catch(_){}if(item.once)combos.splice(i,1);else{item.step=0;item.last=0}}}else if(sameCombo(detail,item.sequence[0])){item.step=1;item.last=t}else item.step=0}}
function combo(index,sequence,callback,opts){var item={index:num(index,0),sequence:arr(sequence),callback:typeof callback==='function'?callback:function(){},timeout:Math.max(1,num(opts&&opts.timeout,500)),once:!!(opts&&opts.once),step:0,last:0};combos.push(item);return{cancel:function(){var i=combos.indexOf(item);if(i>=0)combos.splice(i,1)}}}
function tick(ts){if(!running)return;if(!lastTick||num(ts,0)-lastTick>=cfg.pollRate){lastTick=num(ts,now());poll()}schedule()}
function schedule(){if(!running)return;if(typeof g.requestAnimationFrame==='function'){rafId=g.requestAnimationFrame(tick);return}timerId=setTimeout(function(){tick(now())},cfg.pollRate)}
function start(opts){opts=opts||{};stop();cfg.pollRate=Math.max(1,num(opts.pollRate,16));cfg.deadzone=clamp(opts.deadzone==null?0.1:opts.deadzone,0,1);running=true;lastTick=0;poll();schedule()}
function stop(){running=false;lastTick=0;if(rafId&&typeof g.cancelAnimationFrame==='function')g.cancelAnimationFrame(rafId);if(timerId)clearTimeout(timerId);rafId=0;timerId=0}
return{poll:poll,on:on,off:off,start:start,stop:stop,getState:getState,isPressed:isPressed,getAxis:getAxis,vibrate:vibrate,map:map,combo:combo,deadzone:deadzone,normalize:normalize,profiles:profiles};
})();
if(typeof module!=='undefined') module.exports = BareMetal.Gamepad;
