var BareMetal = (typeof BareMetal !== 'undefined') ? BareMetal : {};
BareMetal.Geo = (function(){
  'use strict';
var g=typeof globalThis!=='undefined'?globalThis:(typeof window!=='undefined'?window:this),R=6371008.8,B='0123456789bcdefghjkmnpqrstuvwxyz';
function n(){return g.navigator||{}}function y(){return n().geolocation}function j(){return g.fetch}function q(v){return Promise.resolve(v)}function fail(m){return Promise.reject(m instanceof Error?m:new Error(m||'Operation failed'))}
function num(v,d){v=Number(v);return isFinite(v)?v:d}function val(v){if(v==null||v==='')return null;v=Number(v);return isFinite(v)?v:null}function rad(v){return num(v,0)*Math.PI/180}function deg(v){return v*180/Math.PI}
function clampLat(v){v=num(v,0);return v>90?90:(v<-90?-90:v)}function wrapLng(v){v=num(v,0);while(v>180)v-=360;while(v<-180)v+=360;return v}
function point(p){var lat,lng;if(!p)return null;if(p.coords)return norm(p);lat=p.lat;if(lat==null)lat=p.latitude;lng=p.lng;if(lng==null)lng=p.lon;if(lng==null)lng=p.longitude;lat=val(lat);lng=val(lng);return lat==null||lng==null?null:{lat:clampLat(lat),lng:wrapLng(lng)}}
function norm(p){var c,lat,lng;if(!p)return null;if(p.coords){c=p.coords;lat=val(c.latitude);lng=val(c.longitude!=null?c.longitude:c.longitude===0?0:c.lon);return lat==null||lng==null?null:{lat:clampLat(lat),lng:wrapLng(lng),accuracy:val(c.accuracy),altitude:val(c.altitude),heading:val(c.heading),speed:val(c.speed),timestamp:num(p.timestamp,Date.now())};}p=typeof p==='object'?p:{};c=point(p);return !c?null:{lat:c.lat,lng:c.lng,accuracy:val(p.accuracy),altitude:val(p.altitude),heading:val(p.heading),speed:val(p.speed),timestamp:num(p.timestamp,Date.now())}}
function posOpts(o){var x={};if(!o||typeof o!=='object')return x;if('enableHighAccuracy'in o)x.enableHighAccuracy=!!o.enableHighAccuracy;if('timeout'in o)x.timeout=o.timeout;if('maximumAge'in o)x.maximumAge=o.maximumAge;return x}
function unsupported(){return fail('Geolocation not supported')}
function getCurrentPosition(opts){var o=y();return o&&o.getCurrentPosition?new Promise(function(resolve,reject){try{o.getCurrentPosition(function(v){v=norm(v);return v?resolve(v):reject(new Error('Invalid position'));},function(err){reject(err||new Error('Unable to get current position'));},posOpts(opts));}catch(err){reject(err);}}):unsupported()}
function watchPosition(callback,opts){var o=y(),onErr=opts&&typeof opts.error==='function'?opts.error:null;if(!o||!o.watchPosition||typeof callback!=='function')return null;try{return o.watchPosition(function(v){v=norm(v);if(v)callback(v);},function(err){if(onErr)onErr(err);},posOpts(opts));}catch(_){return null}}
function clearWatch(watchId){var o=y();if(o&&o.clearWatch&&watchId!=null)try{o.clearWatch(watchId);}catch(_){}}
function distance(p1,p2){var a=point(p1),b=point(p2),dLat,s1,s2,h;if(!a||!b)return 0;if(a.lat===b.lat&&a.lng===b.lng)return 0;dLat=rad(b.lat-a.lat);s1=Math.sin(dLat/2);s2=Math.sin(rad(b.lng-a.lng)/2);h=s1*s1+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*s2*s2;return 2*R*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function bearing(p1,p2){var a=point(p1),b=point(p2),y1,x1;if(!a||!b)return 0;if(a.lat===b.lat&&a.lng===b.lng)return 0;y1=Math.sin(rad(b.lng-a.lng))*Math.cos(rad(b.lat));x1=Math.cos(rad(a.lat))*Math.sin(rad(b.lat))-Math.sin(rad(a.lat))*Math.cos(rad(b.lat))*Math.cos(rad(b.lng-a.lng));return(deg(Math.atan2(y1,x1))+360)%360}
function midpoint(p1,p2){var a=point(p1),b=point(p2),lat1,lat2,lng1,dLng,bx,by,lat3,lng3;if(!a||!b)return null;lat1=rad(a.lat);lng1=rad(a.lng);lat2=rad(b.lat);dLng=rad(b.lng-a.lng);bx=Math.cos(lat2)*Math.cos(dLng);by=Math.cos(lat2)*Math.sin(dLng);lat3=Math.atan2(Math.sin(lat1)+Math.sin(lat2),Math.sqrt((Math.cos(lat1)+bx)*(Math.cos(lat1)+bx)+by*by));lng3=lng1+Math.atan2(by,Math.cos(lat1)+bx);return{lat:deg(lat3),lng:wrapLng(deg(lng3))}}
function boundingBox(center,radiusMeters){var c=point(center),r=num(radiusMeters,0),lat,lng,d,dLng,minLat,maxLat,minLng,maxLng;if(!c)return null;if(r<=0)return{north:c.lat,south:c.lat,east:c.lng,west:c.lng};lat=rad(c.lat);lng=rad(c.lng);d=r/R;minLat=lat-d;maxLat=lat+d;if(minLat<=-Math.PI/2||maxLat>=Math.PI/2||Math.abs(Math.cos(lat))<1e-12){minLat=Math.max(minLat,-Math.PI/2);maxLat=Math.min(maxLat,Math.PI/2);minLng=-Math.PI;maxLng=Math.PI;}else{dLng=Math.asin(Math.sin(d)/Math.cos(lat));minLng=lng-dLng;maxLng=lng+dLng;}return{north:clampLat(deg(maxLat)),south:clampLat(deg(minLat)),east:wrapLng(deg(maxLng)),west:wrapLng(deg(minLng))}}
function onSeg(p,a,b){var x=p.lng,y=p.lat,x1=a.lng,y1=a.lat,x2=b.lng,y2=b.lat,c=(x-x1)*(y2-y1)-(y-y1)*(x2-x1),d;if(Math.abs(c)>1e-10)return false;d=(x-x1)*(x-x2)+(y-y1)*(y-y2);return d<=1e-10}
function isInside(point0,polygon){var p=point(point0),inside=false,i,j,a,b,x,y,xi,yi,xj,yj,hit;if(!p||!(polygon&&polygon.length>=3))return false;x=p.lng;y=p.lat;for(i=0,j=polygon.length-1;i<polygon.length;j=i++){a=point(polygon[i]);b=point(polygon[j]);if(!a||!b)continue;if(onSeg(p,a,b))return true;xi=a.lng;yi=a.lat;xj=b.lng;yj=b.lat;hit=((yi>y)!==(yj>y))&&x<((xj-xi)*(y-yi)/(yj-yi)+xi);if(hit)inside=!inside;}return inside}
function encode(lat,lng,precision){var hash='',idx=0,bit=0,even=true,latMin=-90,latMax=90,lngMin=-180,lngMax=180,mid;lat=clampLat(lat);lng=wrapLng(lng);precision=num(precision,12);if(precision<1)precision=1;while(hash.length<precision){if(even){mid=(lngMin+lngMax)/2;if(lng>=mid){idx=idx*2+1;lngMin=mid;}else{idx*=2;lngMax=mid;}}else{mid=(latMin+latMax)/2;if(lat>=mid){idx=idx*2+1;latMin=mid;}else{idx*=2;latMax=mid;}}even=!even;if(++bit===5){hash+=B.charAt(idx);bit=0;idx=0;}}return hash}
function decode(hash){var even=true,latMin=-90,latMax=90,lngMin=-180,lngMax=180,i,j0,idx,mask,mid,ch=String(hash==null?'':hash).toLowerCase();if(!ch)return null;for(i=0;i<ch.length;i++){idx=B.indexOf(ch.charAt(i));if(idx<0)return null;for(j0=4;j0>=0;j0--){mask=1<<j0;if(even){mid=(lngMin+lngMax)/2;if(idx&mask)lngMin=mid;else lngMax=mid;}else{mid=(latMin+latMax)/2;if(idx&mask)latMin=mid;else latMax=mid;}even=!even;}}return{lat:(latMin+latMax)/2,lng:(lngMin+lngMax)/2,error:{lat:(latMax-latMin)/2,lng:(lngMax-lngMin)/2}}}
function track(opts){var cfg=opts||{},path=[],total=0,id=null,listeners=[],api;function notify(p){var i,s={point:p,path:path.slice(),distance:total};for(i=0;i<listeners.length;i++)try{listeners[i](s);}catch(_){}}function add(p){var last=path.length?path[path.length-1]:null,min=num(cfg.minimumDistance,0),step=last?distance(last,p):0;if(last&&min>0&&step<min)return;if(last)total+=step;path.push(p);notify(p)}function start(){if(id!=null)return api;id=watchPosition(add,cfg);return api}function stop(){if(id!=null){clearWatch(id);id=null;}return api}function getPath(){return path.slice()}function getDistance(){return total}function onUpdate(cb){var off;if(typeof cb!=='function')return function(){};listeners.push(cb);off=function(){var i;for(i=listeners.length-1;i>=0;i--)if(listeners[i]===cb)listeners.splice(i,1);};return off}api={start:start,stop:stop,getPath:getPath,getDistance:getDistance,onUpdate:onUpdate};if(typeof cfg.onUpdate==='function')listeners.push(cfg.onUpdate);if(cfg.autoStart)start();return api}
function json(url){var F=j();return F?F(url,{headers:{Accept:'application/json'}}).then(function(res){if(!res||!res.ok)throw new Error('Request failed');return res.json();}):fail('Fetch not supported')}
function place(v){var box=v&&v.boundingbox||null,lat=val(v&&v.lat),lng=val(v&&(v.lon!=null?v.lon:v.lng)),out;if(lat==null||lng==null)return null;out={lat:lat,lng:lng,displayName:v.display_name||v.name||'',type:v.type||null,className:v.class||null,raw:v};if(box&&box.length===4)out.boundingBox={south:num(box[0],0),north:num(box[1],0),west:num(box[2],0),east:num(box[3],0)};return out}
function geocode(address){var q1=String(address==null?'':address).trim();if(!q1)return q([]);return json('https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=5&q='+encodeURIComponent(q1)).then(function(list){var out=[],i,v;for(i=0;i<(list||[]).length;i++){v=place(list[i]);if(v)out.push(v);}return out;})}
function reverseGeocode(lat,lng){return json('https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&lat='+encodeURIComponent(clampLat(lat))+'&lon='+encodeURIComponent(wrapLng(lng))).then(function(v){return place(v)})}
return{getCurrentPosition:getCurrentPosition,watchPosition:watchPosition,clearWatch:clearWatch,distance:distance,bearing:bearing,midpoint:midpoint,boundingBox:boundingBox,isInside:isInside,encode:encode,decode:decode,track:track,geocode:geocode,reverseGeocode:reverseGeocode};
})();
if(typeof module!=='undefined') module.exports = BareMetal.Geo;
