var BareMetal = (typeof BareMetal !== 'undefined') ? BareMetal : {};
BareMetal.Observe = (function(){
  'use strict';
var g=typeof globalThis!=='undefined'?globalThis:(typeof window!=='undefined'?window:this);
function n(){}function q(v){return Promise.resolve(v)}function f(fn,a,b,c){try{if(typeof fn!=='function')return;if(arguments.length<3)return fn(a);if(arguments.length<4)return fn(a,b);return fn(a,b,c)}catch(_){}}
function y(v,d){v=parseFloat(v);return isNaN(v)?(d||0):v}function d(){return g.document}
function a(v){var o=[],i=0,doc=d();if(!v)return o;if(typeof v==='string')return doc&&doc.querySelectorAll?Array.prototype.slice.call(doc.querySelectorAll(v)):o;if(typeof v.length==='number'&&!v.tagName&&v!==g)return Array.prototype.slice.call(v);return[v]}
function h(el){var r;try{r=el&&el.getBoundingClientRect?el.getBoundingClientRect():null;return{width:r&&r.width!=null?r.width:(el&&el.offsetWidth)||0,height:r&&r.height!=null?r.height:(el&&el.offsetHeight)||0}}catch(_){return{width:(el&&el.offsetWidth)||0,height:(el&&el.offsetHeight)||0}}}
function s(entry,el){var b=entry&&entry.borderBoxSize,c=entry&&entry.contentRect;if(b&&b.length)b=b[0];if(b&&b.inlineSize!=null)return{width:b.inlineSize||0,height:b.blockSize||0};if(c)return{width:c.width||0,height:c.height||0};return h(el)}
function u(o){try{if(o&&o.disconnect)o.disconnect()}catch(_){}}function U(o,el){try{if(o&&o.unobserve)o.unobserve(el)}catch(_){}}
function v(el){var r,w,h2;try{if(!el||!el.getBoundingClientRect)return true;r=el.getBoundingClientRect();w=g.innerWidth||0;h2=g.innerHeight||0;return r.bottom>=0&&r.right>=0&&r.top<=h2&&r.left<=w}catch(_){return true}}
function p(mq,fn){if(!mq||typeof fn!=='function')return n;if(mq.addEventListener){mq.addEventListener('change',fn);return function(){mq.removeEventListener('change',fn)}}if(mq.addListener){mq.addListener(fn);return function(){mq.removeListener(fn)}}return n}
function m(opts){opts=opts||{};return{childList:opts.childList!==false,attributes:!!opts.attributes,characterData:!!opts.characterData,subtree:opts.subtree!==false,attributeFilter:opts.attributeFilter}}
function resize(el,callback,opts){var ro=null,off=n,t=0,box=opts&&opts.box;function emit(entry){var z=s(entry,el),data={width:z.width,height:z.height,entry:entry||null};if(opts&&opts.debounce){clearTimeout(t);t=g.setTimeout(function(){f(callback,data)},opts.debounce)}else f(callback,data)}if(!el)return{disconnect:n};if(g.ResizeObserver)try{ro=new g.ResizeObserver(function(entries){var i=0;for(;i<(entries||[]).length;i++)if(!entries[i]||entries[i].target===el)emit(entries[i])});if(box)ro.observe(el,{box:box});else ro.observe(el)}catch(_){ro=null}if(!ro&&g.addEventListener){off=function(){emit(null)};g.addEventListener('resize',off)}if(!ro)emit(null);return{disconnect:function(){clearTimeout(t);if(off!==n&&g.removeEventListener)g.removeEventListener('resize',off);u(ro)}}}
function intersection(el,callback,opts){var io=null,off=n;opts=opts||{};function emit(entry){var hit=!!(entry&&entry.isIntersecting),ratio=entry&&entry.intersectionRatio!=null?entry.intersectionRatio:(hit?1:0);f(callback,{isIntersecting:hit,ratio:ratio,entry:entry||null})}function ping(){emit({target:el,isIntersecting:v(el),intersectionRatio:v(el)?1:0})}if(!el)return{disconnect:n};if(g.IntersectionObserver)try{io=new g.IntersectionObserver(function(entries){var i=0;for(;i<(entries||[]).length;i++)if(!entries[i]||entries[i].target===el)emit(entries[i])},{root:opts.root||null,rootMargin:opts.rootMargin||'0px',threshold:opts.threshold!=null?opts.threshold:0});io.observe(el)}catch(_){io=null}if(!io&&g.addEventListener){off=ping;g.addEventListener('scroll',off,true);g.addEventListener('resize',off);ping()}else if(!io)ping();return{disconnect:function(){if(off!==n&&g.removeEventListener){g.removeEventListener('scroll',off,true);g.removeEventListener('resize',off)}u(io)}}}
function mutation(el,callback,opts){var mo=null;if(!el||!g.MutationObserver)return{disconnect:n};try{mo=new g.MutationObserver(function(records){f(callback,records||[],mo,el)});mo.observe(el,m(opts))}catch(_){mo=null}return{disconnect:function(){u(mo)}}}
function lazyLoad(selector,opts){opts=opts||{};var list=a(selector),io=null,clean=[],gone=false;function swap(el,entry){var tag=((el&&el.tagName)||'').toLowerCase(),done=false,off=n;function finish(){if(done||gone)return;done=true;off();if(el.classList)el.classList.add('loaded');f(opts.onLoad,el,entry)}if(!el||el.__bmLazyLoaded)return;el.__bmLazyLoaded=1;if((tag==='img'||tag==='iframe')&&el.addEventListener){off=function(){el.removeEventListener('load',finish);el.removeEventListener('error',finish)};el.addEventListener('load',finish);el.addEventListener('error',finish);clean.push(off)}if(el.getAttribute&&el.getAttribute('data-srcset')!=null)el.setAttribute('srcset',el.getAttribute('data-srcset'));if(el.getAttribute&&el.getAttribute('data-sizes')!=null)el.setAttribute('sizes',el.getAttribute('data-sizes'));if(el.getAttribute&&el.getAttribute('data-src')!=null)el.setAttribute('src',el.getAttribute('data-src'));if(tag!=='img'&&tag!=='iframe')finish();else if(tag==='img'&&el.complete)finish()}
if(g.IntersectionObserver)try{io=new g.IntersectionObserver(function(entries){var i=0,e;for(;i<(entries||[]).length;i++){e=entries[i];if(e&&e.isIntersecting){swap(e.target,e);U(io,e.target)}}},{root:opts.root||null,rootMargin:opts.rootMargin||'200px 0px',threshold:opts.threshold!=null?opts.threshold:0});list.forEach(function(el){if(el)io.observe(el)})}catch(_){io=null}if(!io)list.forEach(function(el){swap(el,null)});return{destroy:function(){gone=true;clean.forEach(function(fn){f(fn)});u(io)}}}
function infinite(sentinel,loadMore,opts){var inside=false,busy=false,watch=intersection(sentinel,function(state){var out;if(state.isIntersecting){if(!inside&&!busy){inside=true;busy=true;out=f(loadMore,state.entry);if(out&&typeof out.then==='function')out.then(function(){busy=false},function(){busy=false});else busy=false}}else inside=false},opts);return{destroy:function(){watch.disconnect()}}}
function sticky(el,opts){opts=opts||{};var doc=d(),sent=null,watch={disconnect:n},stuck=false,parent=el&&el.parentNode,top=opts.top!=null?y(opts.top,0):y(g.getComputedStyle&&el?g.getComputedStyle(el).top:0,0);if(doc&&doc.createElement&&el&&parent){sent=doc.createElement('div');sent.setAttribute('aria-hidden','true');sent.style.cssText='position:relative;display:block;height:1px;margin-top:-1px;visibility:hidden;pointer-events:none';parent.insertBefore(sent,el);watch=intersection(sent,function(state){var next=!state.isIntersecting;if(next!==stuck){stuck=next;if(stuck)f(opts.onStick,el,state.entry);else f(opts.onUnstick,el,state.entry)}},{root:opts.root||null,rootMargin:'-'+(top+1)+'px 0px 0px 0px',threshold:opts.threshold!=null?opts.threshold:[0,1]})}return{destroy:function(){watch.disconnect();if(sent&&sent.parentNode)sent.parentNode.removeChild(sent)},get isStuck(){return stuck}}}
function viewport(el){return new Promise(function(resolve){var stop;if(!el)return resolve();stop=intersection(el,function(state){if(state.isIntersecting){stop.disconnect();resolve()}},{threshold:0})})}
function trackSize(el,callback,opts){opts=opts||{};var last=h(el),t=0,watch=resize(el,function(data){last={width:data.width,height:data.height};if(opts.debounce){clearTimeout(t);t=g.setTimeout(function(){f(callback,last,data.entry)},opts.debounce)}else f(callback,last,data.entry)},{box:opts.box});return{disconnect:function(){clearTimeout(t);watch.disconnect()},getSize:function(){return{width:last.width,height:last.height}}}}
function breakpoint(el,breakpoints,callback){var keys=Object.keys(breakpoints||{}).sort(function(a2,b2){return y(breakpoints[a2],0)-y(breakpoints[b2],0)}),current=null,watch;function pick(w){var i=0,name=keys[0]||null;for(;i<keys.length;i++)if(w>=y(breakpoints[keys[i]],0))name=keys[i];return name}function emit(size,entry){var name=pick(size.width);if(name!==current){current=name;f(callback,name,{width:size.width,height:size.height,entry:entry||null})}}emit(h(el),null);watch=trackSize(el,function(size,entry){emit(size,entry)});return{disconnect:function(){watch.disconnect()}}}
function animateOnScroll(els,opts){opts=opts||{};var list=a(els),io=null,klass=opts['class']||'in-view';if(g.IntersectionObserver)try{io=new g.IntersectionObserver(function(entries){var i=0,e,el;for(;i<(entries||[]).length;i++){e=entries[i];el=e&&e.target;if(!el||!el.classList)continue;if(e.isIntersecting){el.classList.add(klass);if(opts.once)U(io,el)}else if(!opts.once)el.classList.remove(klass)}},{root:opts.root||null,rootMargin:opts.rootMargin||'0px',threshold:opts.threshold!=null?opts.threshold:0});list.forEach(function(el){if(el)io.observe(el)})}catch(_){io=null}if(!io)list.forEach(function(el){if(el&&el.classList)el.classList.add(klass)});return{destroy:function(){u(io)}}}
function mediaQuery(query,callback){var mq=null,off=n,state=false;try{mq=g.matchMedia?g.matchMedia(query):null}catch(_){mq=null}state=!!(mq&&mq.matches);function on(ev){state=!!(ev&&ev.matches);f(callback,state,ev||mq)}if(mq){off=p(mq,on);f(callback,state,mq)}else f(callback,false,null);return{destroy:function(){off()},get matches(){return state}}}
function mutationStream(el,opts){var queue=[],waiters=[],closed=false,mo=null,it,key=typeof Symbol!=='undefined'&&Symbol.asyncIterator?Symbol.asyncIterator:'@@asyncIterator';function push(records){var i=0,next;for(;i<(records||[]).length;i++)if(waiters.length){next=waiters.shift();next({value:records[i],done:false})}else queue.push(records[i])}function next(){if(queue.length)return q({value:queue.shift(),done:false});if(closed)return q({done:true});return new Promise(function(resolve){waiters.push(resolve)})}function close(){closed=true;while(waiters.length)waiters.shift()({done:true})}if(el&&g.MutationObserver)try{mo=new g.MutationObserver(push);mo.observe(el,m(opts))}catch(_){mo=null}it={next:next,disconnect:function(){u(mo);close()}};it[key]=function(){return this};return it}
return{resize:resize,intersection:intersection,mutation:mutation,lazyLoad:lazyLoad,infinite:infinite,sticky:sticky,viewport:viewport,trackSize:trackSize,breakpoint:breakpoint,animateOnScroll:animateOnScroll,mediaQuery:mediaQuery,mutationStream:mutationStream};
})();
if(typeof module!=='undefined') module.exports = BareMetal.Observe;
